# Generated by Django 4.2.3 on 2023-08-07 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UnitCalculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudobillmodel',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
